<script lang="ts">
  import { resolve } from "$app/paths";
  import ObjectCard from "$lib/components/ObjectCard.svelte";
  import Seo from "$lib/components/Seo.svelte";
  import { fixedObjects } from "$lib/data/objects";
  import { chapters } from "$lib/data/story";
  import { chapterPath } from "$lib/links";

  const groups = chapters
    .map((title, page) => ({
      page,
      title,
      objects: fixedObjects.filter((object) => object.chapter === page),
    }))
    .filter((group) => group.objects.length > 0);
</script>

<Seo
  title="Mine objects"
  description="All {fixedObjects.length} hand-made mine objects in Idle Mine Beyond, from Mud to THE UNIVERSE, grouped by Story chapter."
/>

<header class="page-head">
  <p class="eyebrow">Mine objects</p>
  <h1>From Mud to THE UNIVERSE</h1>
  <p class="lede">
    The game has {fixedObjects.length} hand-made objects. Between them, and after
    THE UNIVERSE, objects are generated by formula; look any of those up in the
    <a href={resolve("/wiki/explorer/")}>object explorer</a>.
  </p>
</header>

{#each groups as group (group.page)}
  <section class="group" aria-labelledby="chapter-{group.page}">
    <div class="group-head">
      <h2 id="chapter-{group.page}">
        <span class="chapter-number">Chapter {group.page + 1}</span>
        {group.title}
      </h2>
      <a href={resolve(chapterPath(group.page))}>Read the chapter</a>
    </div>
    <ul class="grid">
      {#each group.objects as object (object.level)}
        <li><ObjectCard {object} /></li>
      {/each}
    </ul>
  </section>
{/each}

<style>
  .page-head {
    margin-bottom: 2.5rem;
  }

  .group {
    margin-top: 3rem;
  }

  .group-head {
    display: flex;
    align-items: baseline;
    justify-content: space-between;
    gap: 1rem;
    border-bottom: 1px solid var(--line);
    padding-bottom: 0.6rem;
    margin-bottom: 1.25rem;
  }

  h2 {
    font-size: 1.45rem;
    margin: 0;
  }

  .chapter-number {
    display: block;
    font-family: var(--font-body);
    font-size: 0.75rem;
    letter-spacing: 0.12em;
    text-transform: uppercase;
    color: var(--text-faint);
    margin-bottom: 0.3rem;
  }

  .group-head a {
    font-size: 0.95rem;
    white-space: nowrap;
  }

  .grid {
    list-style: none;
    margin: 0;
    padding: 0;
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(8.5rem, 1fr));
    gap: 0.75rem;
  }
</style>
